name: Dependabot Automation
description: Automate your Dependabot busywork
author: Ghalactic
inputs:
  token:
    description: >-
      The GitHub token to use.
    default: ${{ github.token }}
branding:
  icon: package
  color: blue
runs:
  using: node20
  main: dist/main.js
